apiVersion: v1
kind: Secret
metadata:
  name: person-api-secret
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: "true"
type: opaque
data:
  host: aG9zdG5hbWUuY29t
  caCrt: dGVzdGNlcnQ=
  token: dGVzdHRva2Vu
