spring:
  data:
    rest:
      basePath: /persons/api/v1
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: testUser
    password: testPassword
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-ui # default path: h2-console

server:
  servlet:
    context-path: /persons/api/v1

springdoc:
  packages-to-scan:
  - com.dishant.person.api
  api-docs:
    path: /docs
  swagger-ui:
    operations-sorter: method

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
        - health

---
spring:
  profiles: test

security:
  basic:
    enabled: false
