name: Create Release

on:
  push:
    branches: [ main ]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: "Update Version"
        id: update-version
        uses: google-github-actions/release-please-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-type: maven
          token: ${{ secrets.GITHUB_TOKEN }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
          default-branch: main
      - name: "Create release"
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.update-version.outputs.tag_name }}
          release_name: ${{ steps.update-version.outputs.major }}.${{ steps.update-version.outputs.minor }}.${{ steps.update-version.outputs.patch }}
