name: Create Release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create a Release
    steps:
#     - uses: actions/checkout@v2
#     - uses: elgohr/Github-Release-Action@master
#       env:
#         GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
    - uses: alice-biometrics/release-creator/@v1.0.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        version: 'v2.0.0'
        branch: main
        description: 'Version :ok_hand:'
