name: Create Release
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Create a Release
    steps:
    - uses: alice-biometrics/release-creator/@v1.0.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        version: 'inherit'
        branch: main
        description: 'inherit'
