name: CI - Create Release and Publish
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Bump Version
      id: bump
      uses: remorses/bump-version@js
      with:
        version_file: ./VERSION
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Update version in pom.xml (Release only)
      run: mvn -B versions:set -DnewVersion=${{ steps.bump.outputs.version }} -DgenerateBackupPoms=false  --file pom.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml install
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/dishantkamble -Dtoken=$GH_TOKEN
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Create Release
      uses: Roang-zero1/github-create-release-action@v2
      with:
        created_tag: ${{ steps.bump.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.bump.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
